"""Add gamification fields to User

Revision ID: 1d7f1d4c7ce8
Revises: 17d87c469e59
Create Date: 2026-05-16 12:40:35.392419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7f1d4c7ce8'
down_revision = '17d87c469e59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('longest_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_study_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('exp_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'exp_points')
    op.drop_column('users', 'last_study_date')
    op.drop_column('users', 'longest_streak')
    op.drop_column('users', 'current_streak')
    # ### end Alembic commands ###
